name: Mypy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install --upgrade pip
    - run: pip install mypy
    - run: mypy --strict $(git ls-files '*.py')
